Feature/school-292/invite-parent
LamArt/open-schools-platform pull request #103
Opened 2022-10-04 12:50 UTC by Ivan228777

Added invite-parent and invite-parent-invitations-list API handlers, covered them with tests.

2022-10-04 15:26 UTC, zavarin-michael requested changes

2022-10-04 15:26 UTC, zavarin-michael commented on open_schools_platform/common/services.py
> +                if query.body is None:
you can write like this:
not without_body and query.body is None

2022-10-05 15:20 UTC, Ivan228777 commented on open_schools_platform/query_management/queries/models.py
> +    body_ct = models.ForeignKey(ContentType, related_name="body_ct", null=True, blank=True, on_delete=models.CASCADE)
We need it for making empty body in Query

2022-10-05 15:25 UTC, Ivan228777 commented on open_schools_platform/query_management/queries/tests/utils.py
> +    return query
Also we need this variable for proper work of create_testdata_in_db function.

2022-10-05 15:29 UTC, zavarin-michael commented on open_schools_platform/query_management/queries/models.py
> +    body_ct = models.ForeignKey(ContentType, related_name="body_ct", null=True, blank=True, on_delete=models.CASCADE)
it is strange, this comment was deleted by me
okay, understandable

2022-10-05 15:31 UTC, zavarin-michael commented on open_schools_platform/query_management/queries/tests/utils.py
> +    return query
okay but rename it
object_index_get or or something like that

2022-10-05 15:39 UTC, zavarin-michael requested changes

2022-10-05 15:39 UTC, zavarin-michael commented on open_schools_platform/common/services.py
> +        if query.recipient is None or query.sender is None or without_body is None and query.body is None:
why without_body is None?)
bool should be false or true

2022-10-05 15:49 UTC, zavarin-michael approved these changes

2022-10-05 15:50 UTC, merged