Feature/school 442/adding export
LamArt/open-schools-platform pull request #121
Opened 2022-11-16 10:37 UTC by Feazom

2022-11-16 15:44 UTC, zavarin-michael requested changes

2022-11-16 15:54 UTC, Feazom commented on open_schools_platform/student_management/students/exports.py
> +        return student.circle.name
This replaces the circle id in the export with the name of the circle. [docs]( https://django-import-export.readthedocs.io/en/latest/getting_started.html#advanced-data-manipulation-on-export)

2022-11-16 15:57 UTC, Feazom commented on open_schools_platform/photo_management/photos/tests/views/test_photo_update_exceptions.py
> -        self.assertEqual(401, without_credentials_response.status_code)
this is a redundant test, you asked me to remove it before, i decided to do it here

2022-11-19 09:32 UTC, zavarin-michael approved these changes

2022-11-19 09:32 UTC, merged