Fix/school 153/dev refactoring
LamArt/open-schools-platform pull request #24
Opened 2022-06-15 20:56 UTC by mzavarka

2022-06-18 13:23 UTC, Ivan228777 approved these changes
Great!

2022-06-18 13:35 UTC, Ivan228777 commented on open_schools_platform/user_management/authentication/apis.py
> -from ...errors.services import NotAcceptableException
Maybe it is better to write whole path to imported object?

2022-06-21 19:58 UTC, IlyaBat9 requested changes
This is cool PR.

2022-06-21 19:58 UTC, IlyaBat9 commented on open_schools_platform/common/filters.py
> +    ORDER_DATE_TIME = "-created_at"
Date with a girl?

2022-06-21 19:58 UTC, IlyaBat9 commented on open_schools_platform/user_management/users/constants.py
> +    PASSWORD_LENGTH = 5
In open_schools_platform/user_management/users/serializers.py (51 str) writes that minimum length is equal 6.

2022-06-21 19:58 UTC, IlyaBat9 commented on open_schools_platform/user_management/users/tests/views/test_users_exceptions.py
> +        self.assertEqual(500, response.status_code)
500 is not for application error. This is host error.

2022-06-21 20:24 UTC, IlyaBat9 approved these changes

2022-06-21 20:25 UTC, merged