Feature/school 32/registration
LamArt/open-schools-platform pull request #3
Opened 2022-04-09 11:09 UTC by zavarin-michael

user registration mvp

2022-04-09 11:40 UTC, IlyaBat9 requested changes

2022-04-09 11:40 UTC, IlyaBat9 commented on LICENSE
> +Copyright (c) 2020 HackSoft
We are use this license? Change copyright?

2022-04-09 11:40 UTC, IlyaBat9 commented on config/settings/celery.py
> +CELERY_TIMEZONE = 'UTC'
This is not ok.

2022-04-13 10:07 UTC, zavarin-michael commented on .pre-commit-config.yaml
> +          verbose: true
Это mvp gре коммит конфига. Возможно стоит дополнить blackом. Главное не перегружать

2022-04-13 10:19 UTC, zavarin-michael commented on open_schools_platform/user_management/authentication/tests/apis/test_user_login.py
> +            "name": "Vasya",
Should we use Slavic names in tests?

2022-04-13 10:54 UTC, zavarin-michael commented on open_schools_platform/user_management/users/constants.py
> +    LIVE_TIME = datetime_lib.timedelta(minutes=7)
7 minutes?

2022-04-13 11:04 UTC, zavarin-michael commented on open_schools_platform/user_management/users/serializers.py
> +    recaptcha = serializers.CharField(
Should we add serializer on recaptcha? 
Actually, firebase can do it instead of us

2022-04-13 11:59 UTC, zavarin-michael commented on open_schools_platform/user_management/users/services.py
> +            session=json.loads(response.content.decode("utf-8"))["sessionInfo"],
Needed an util that decode any responses

2022-04-13 12:01 UTC, zavarin-michael commented on open_schools_platform/user_management/users/tests/constants/test_firebase_urls.py
> +        self.assertEqual(403, response.status_code)
Stupid tests. We should come up with a replacement or delete them.

2022-04-13 12:02 UTC, zavarin-michael commented on open_schools_platform/user_management/users/tests/services/test_user_create.py
> +                name="Ivan",
Same issue above

2022-04-16 09:24 UTC, IlyaBat9 approved these changes

2022-04-16 09:24 UTC, IlyaBat9 commented on open_schools_platform/user_management/users/tests/services/test_user_create.py
> +            password="qwe",
Change to more i8n name, phone. And password length not small? Why do not raise error?

2022-04-16 09:24 UTC, IlyaBat9 commented on requirements.txt
> +-r requirements/local.txt
Add instructions where to point that this string need to change for production.

2022-04-16 09:24 UTC, IlyaBat9 commented on open_schools_platform/user_management/authentication/tests/apis/test_user_login.py
> +            "name": "Vasya",
No, not should.

2022-04-16 09:25 UTC, IlyaBat9 commented on open_schools_platform/user_management/users/tests/services/test_user_create.py
> +            password="qwe",
Add to task list

2022-04-16 09:25 UTC, IlyaBat9 commented on requirements.txt
> +-r requirements/local.txt
Add to task list

2022-04-16 09:29 UTC, merged