Creating a user inside the Organization Invite, if it does not exist
LamArt/open-schools-platform pull request #48
Opened 2022-07-13 14:09 UTC by Pechenka472

2022-07-13 18:56 UTC, zavarin-michael requested changes

2022-07-13 18:56 UTC, zavarin-michael commented on open_schools_platform/organization_management/employees/selectors.py
> -    return EmployeeProfileFilter(filters, qs).qs.first()
why it is deleted?

2022-07-13 18:56 UTC, zavarin-michael commented on open_schools_platform/organization_management/employees/services.py
>      add_user = get_user(filters={"phone": phone})
add_user?
this variable should be renamed

2022-07-13 18:56 UTC, zavarin-michael commented on open_schools_platform/organization_management/organizations/models.py
> +            query.body.save()  # type: ignore
add if wiht such expression
1) sender - Organization
2) recipient - Employee

it is for skipping queries with others parametrs
in "wrong" case we should raise 400 exception

2022-07-14 11:56 UTC, Pechenka472 commented on open_schools_platform/organization_management/employees/selectors.py
> -    return EmployeeProfileFilter(filters, qs).qs.first()
because it is not used

2022-07-18 18:23 UTC, zavarin-michael requested changes

2022-07-18 18:23 UTC, zavarin-michael commented on open_schools_platform/organization_management/employees/filters.py
> +    user_id = CharFilter(field_name="employee_profile__user__id", lookup_expr="icontains")
it is not necessary to define user_id and organization_id 
you can do it with "fields" list in Meta class, I believe in you

2022-07-18 18:23 UTC, zavarin-michael commented on open_schools_platform/organization_management/employees/filters.py
> +    user_id = CharFilter(field_name="employee_profile__user__id", lookup_expr="icontains")
somewhere in handlers there can be some mistakes that is realated with this filter
fix VIEWS and SERVICES code too

2022-07-21 16:27 UTC, zavarin-michael approved these changes

2022-07-21 16:27 UTC, merged