fix/geodjango-srid
LamArt/open-schools-platform pull request #91
Opened 2022-08-31 20:21 UTC by Ivan228777

2022-09-01 18:05 UTC, zavarin-michael requested changes

2022-09-01 18:05 UTC, zavarin-michael commented on open_schools_platform/organization_management/circles/migrations/0004_reverse_location.py
> +        migrations.RunPython(reverse_circles_location)
also make return migrations method as second argument in RunPython
like that: migrations.RunPython(create_profiles_for_employees, delete_employees_profiles),

2022-09-02 05:10 UTC, zavarin-michael approved these changes

2022-09-02 05:10 UTC, merged

2022-09-17 07:24 UTC, Ivan228777 commented
[SCHOOL-330]