Feature/circles-order
LamArt/open-schools-platform pull request #94
Opened 2022-09-11 15:32 UTC by Ivan228777

2022-09-11 18:23 UTC, zavarin-michael requested changes

2022-09-11 18:23 UTC, zavarin-michael commented on open_schools_platform/organization_management/circles/selectors.py
> +    CircleFilter.ORDER_FIELD = None  # type: ignore
I wanted it in other way

2022-09-11 18:23 UTC, zavarin-michael commented on open_schools_platform/organization_management/circles/selectors.py
>      circles = CircleFilter(filters, qs).qs
define order_by functionallty here not in filter

2022-09-11 18:23 UTC, zavarin-michael commented on open_schools_platform/organization_management/circles/filters.py
> +    return qs.order_by(GeometryDistance("location", convert_str_to_point(value)))
this logic should be in selector

2022-09-11 18:34 UTC, Ivan228777 commented on open_schools_platform/organization_management/circles/selectors.py
> +    CircleFilter.ORDER_FIELD = None  # type: ignore
I had to use type: ignore here because mypy doesn't allow to set None value for ORDER_FIELD (because it is string initially)

2022-09-13 14:49 UTC, zavarin-michael approved these changes

2022-09-13 14:50 UTC, merged