Make models soft-deletable or undeletable
LamArt/open-schools-platform pull request #99
Opened 2022-09-21 13:24 UTC by timka-byzov

2022-11-05 08:49 UTC, IlyaBat9 commented
+SCHOOL-383

2022-11-05 08:55 UTC, IlyaBat9 commented on requirements/base.txt
>  whitenoise==6.2.0
Why this file have strange structure? Is important empty line? And order of lines? May be make format this file with comment?

2022-11-06 15:24 UTC, zavarin-michael requested changes

2022-11-07 15:18 UTC, zavarin-michael approved these changes

2022-11-07 15:18 UTC, merged